name: Build-n-Release

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - '**.flux'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Get Cache TS
      if: github.event_name != 'pull_request'
      id: cachetime
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: 'YYYYMMDD'
        
    - name: Cache Flux Build
      id: cache-flux-go
      uses: actions/cache@v3
      with:
        path: |
          flux
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-flux-${{ hashFiles('**/fluxpipe-server.go') }}
        restore-keys: |
          ${{ runner.os }}-flux-
        
    - name: Get Flux
      if: steps.cache-flux-go.outputs.cache-hit != 'true'
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'adubovikov'
        repository: 'flux'
        
    - name: Compile Flux
      if: steps.cache-flux-go.outputs.cache-hit != 'true'
      run: |
        cd flux
        make
        
    - name: Build Fluxpipe
      run: |
        sed -i 's|/usr/src/|/home/runner/work/fluxpipe/fluxpipe/|g' flux.pc
        pwd
        ls -alF
        ./build.sh
        
    - name: Compress Fluxpipe
      run: |
        strip fluxpipe-server
        upx fluxpipe-server
        
    - name: Get Timestamp
      if: github.event_name != 'pull_request'
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: 'YYYYMMDDHHmmss'
        
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            fluxpipe-server
        tag_name: v${{ steps.time.outputs.time }}
        release_name: fluxpipe_v${{ steps.time.outputs.time }}
        draft: false
        prerelease: false
        overwrite: true   
        
  dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: |
             ghcr.io/metrico/fluxpipe:latest
